// <auto-generated />
using System;
using Follow_Extremist.Data.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Follow_Extremist.Data.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20261010103715_AddDeviceEnrollIdAndHardwareFields")]
    partial class AddDeviceEnrollIdAndHardwareFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Follow_Extremist.Core.AttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttendanceDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeviceEnrollId")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWantedAtTime")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NextFollowDateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PrintedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VerifyType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ElementId");

                    b.ToTable("AttendanceLog");
                });

            modelBuilder.Entity("Follow_Extremist.Core.ElementAddInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElementInfoId")
                        .HasColumnType("int");

                    b.Property<string>("ElementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElementRelationNationalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ElementRelationNationalIDImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ElemmentRelationImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NameRelationElement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ElementInfoId");

                    b.ToTable("ElementAddInfo");
                });

            modelBuilder.Entity("Follow_Extremist.Core.ElementCases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CasesData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ElementDateJail")
                        .HasColumnType("datetime2");

                    b.Property<string>("ElementDateRelease")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElementFollowNew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElementInfoId")
                        .HasColumnType("int");

                    b.Property<string>("ElementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElementStateJailOrNot")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ElementInfoId");

                    b.ToTable("ElementCases");
                });

            modelBuilder.Entity("Follow_Extremist.Core.ElementFingerprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<int>("FingerIndex")
                        .HasColumnType("int");

                    b.Property<string>("FingerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.ToTable("ElementFingerprint");
                });

            modelBuilder.Entity("Follow_Extremist.Core.ElementFollowAdd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFollow")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElementInfoId")
                        .HasColumnType("int");

                    b.Property<string>("ElementName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ElementInfoId");

                    b.ToTable("ElementFollowAdd");
                });

            modelBuilder.Entity("Follow_Extremist.Core.ElementInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateFollowNext")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFollowNow")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFollowStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeviceEnrollId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ElementImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ElementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookAcount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FollowDaysCount")
                        .HasColumnType("int");

                    b.Property<string>("FollowState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("NationalIdImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrisonedOrnot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonEndFollow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegulatoryStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ElementInfo");
                });

            modelBuilder.Entity("Follow_Extremist.Core.ElementInfoView", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFollowNext")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFollowNow")
                        .HasColumnType("datetime2");

                    b.Property<string>("ElementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("ElementInfoView", (string)null);
                });

            modelBuilder.Entity("Follow_Extremist.Core.ElementWantedStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<bool>("IsWanted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WantedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("WantedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WantedReason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ElementId")
                        .IsUnique();

                    b.ToTable("ElementWantedStatus");
                });

            modelBuilder.Entity("Follow_Extremist.Core.FingerprintDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FingerprintDevice");
                });

            modelBuilder.Entity("Follow_Extremist.Core.PrintSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoPrintOnAttendance")
                        .HasColumnType("bit");

                    b.Property<string>("FooterText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaperWidthMm")
                        .HasColumnType("int");

                    b.Property<int>("PrintCopies")
                        .HasColumnType("int");

                    b.Property<string>("PrinterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrinterType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScreenDurationSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("ShowBarcode")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowNationalId")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowNextFollowDate")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PrintSetting");
                });

            modelBuilder.Entity("Follow_Extremist.Core.SystemRecords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemRecords");
                });

            modelBuilder.Entity("Follow_Extremist.Core.TodayAttendanceView", b =>
                {
                    b.Property<DateTime>("AttendanceDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AttendanceLogId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<string>("ElementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWanted")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextFollowDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_TodayAttendance", (string)null);
                });

            modelBuilder.Entity("Follow_Extremist.Core.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Follow_Extremist.Core.UsersRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.Property<bool>("Value")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UsersId");

                    b.ToTable("UsersRoles");
                });

            modelBuilder.Entity("Follow_Extremist.Core.AttendanceLog", b =>
                {
                    b.HasOne("Follow_Extremist.Core.FingerprintDevice", "FingerprintDevice")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Follow_Extremist.Core.ElementInfo", "ElementInfo")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElementInfo");

                    b.Navigation("FingerprintDevice");
                });

            modelBuilder.Entity("Follow_Extremist.Core.ElementAddInfo", b =>
                {
                    b.HasOne("Follow_Extremist.Core.ElementInfo", "ElementInfo")
                        .WithMany("ElementAddInfo")
                        .HasForeignKey("ElementInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElementInfo");
                });

            modelBuilder.Entity("Follow_Extremist.Core.ElementCases", b =>
                {
                    b.HasOne("Follow_Extremist.Core.ElementInfo", "ElementInfo")
                        .WithMany("ElementCases")
                        .HasForeignKey("ElementInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElementInfo");
                });

            modelBuilder.Entity("Follow_Extremist.Core.ElementFingerprint", b =>
                {
                    b.HasOne("Follow_Extremist.Core.ElementInfo", "ElementInfo")
                        .WithMany("ElementFingerprints")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElementInfo");
                });

            modelBuilder.Entity("Follow_Extremist.Core.ElementFollowAdd", b =>
                {
                    b.HasOne("Follow_Extremist.Core.ElementInfo", "ElementInfo")
                        .WithMany("ElementFollowAdd")
                        .HasForeignKey("ElementInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElementInfo");
                });

            modelBuilder.Entity("Follow_Extremist.Core.ElementWantedStatus", b =>
                {
                    b.HasOne("Follow_Extremist.Core.ElementInfo", "ElementInfo")
                        .WithOne("ElementWantedStatus")
                        .HasForeignKey("Follow_Extremist.Core.ElementWantedStatus", "ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElementInfo");
                });

            modelBuilder.Entity("Follow_Extremist.Core.UsersRoles", b =>
                {
                    b.HasOne("Follow_Extremist.Core.Users", "Users")
                        .WithMany("UsersRoles")
                        .HasForeignKey("UsersId");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Follow_Extremist.Core.ElementInfo", b =>
                {
                    b.Navigation("AttendanceLogs");

                    b.Navigation("ElementAddInfo");

                    b.Navigation("ElementCases");

                    b.Navigation("ElementFingerprints");

                    b.Navigation("ElementFollowAdd");

                    b.Navigation("ElementWantedStatus");
                });

            modelBuilder.Entity("Follow_Extremist.Core.FingerprintDevice", b =>
                {
                    b.Navigation("AttendanceLogs");
                });

            modelBuilder.Entity("Follow_Extremist.Core.Users", b =>
                {
                    b.Navigation("UsersRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
